spring.application.name=Session16_TMDT

# k?t n?i v?i mySQL
spring.datasource.url=jdbc:mysql://localhost:3306/session16_tmdt?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=14102005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# s? d?ng JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf c?u hình
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


server.servlet.session.timeout=10m